"use strict";
const CONFIG={
  recent:{arrival:"https://www.mardep.gov.hk/e_files/en/opendata/RP05005i.XML",departure:"https://www.mardep.gov.hk/e_files/en/opendata/RP05505i.XML"},
  report:{arrival:"https://www.mardep.gov.hk/e_files/en/pub_services/RP05005.XML",departure:"https://www.mardep.gov.hk/e_files/en/pub_services/RP05505.XML"},
  future:{arrival:"https://www.mardep.gov.hk/e_files/en/pub_services/RP04005.XML",departure:"https://www.mardep.gov.hk/e_files/en/pub_services/RP04505.XML"},
  historicalApi:"https://app.data.gov.hk/v1/historical-archive/get-file",maxDays:20,timeoutMs:14000,retries:3,concurrency:4,
  proxies:[u=>`https://api.allorigins.win/raw?url=${encodeURIComponent(u)}`,u=>`https://corsproxy.io/?url=${encodeURIComponent(u)}`]
};
const $=id=>document.getElementById(id); let currentData=[]; let activeController=null;
document.addEventListener("DOMContentLoaded",()=>{setDefaultDates();$("useLast36h").addEventListener("change",()=>selectMode("recent"));$("useFuture").addEventListener("change",()=>selectMode("future"));$("searchBtn").addEventListener("click",performSearch);$("clearBtn").addEventListener("click",clearSearch);$("vesselName").addEventListener("keydown",e=>{if(e.key==="Enter")performSearch()});selectMode("recent",true)});
function localYMD(d=new Date()){return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Hong_Kong",year:"numeric",month:"2-digit",day:"2-digit"}).format(d)}
function addDays(s,n){const [y,m,d]=s.split("-").map(Number),x=new Date(Date.UTC(y,m-1,d+n));return x.toISOString().slice(0,10)}
function setDefaultDates(){const t=localYMD();$("startDate").value=addDays(t,-1);$("endDate").value=t}
function selectMode(mode,initial=false){const a=$("useLast36h"),f=$("useFuture");if(mode==="recent"&&a.checked)f.checked=false;if(mode==="future"&&f.checked)a.checked=false;const special=a.checked||f.checked;$("startDate").disabled=special;$("endDate").disabled=special;$("modeHint").textContent=f.checked?"未來船期直接讀取海事處最新 XML，日期範圍不適用。":a.checked?"最近 36 小時資料直接讀取海事處最新公開資料。":"歷史資料可選擇最多 20 天，最新歷史存檔一般為昨天。";if(!initial)clearResults()}
function mode(){return $("useFuture").checked?"future":$("useLast36h").checked?"recent":"historical"}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function log(msg,type="info"){const e=document.createElement("div"),time=new Date().toLocaleTimeString("zh-HK",{hour12:false});e.innerHTML=`<span class="log-time">[${escapeHTML(time)}]</span> <span class="log-${type}">${escapeHTML(msg)}</span>`;$("logPanel").appendChild(e);$("logWrap").classList.add("show");$("logPanel").scrollTop=$("logPanel").scrollHeight}
function escapeHTML(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function setProgress(done,total,text){$("progressBar").style.width=`${Math.max(8,Math.round(done/Math.max(total,1)*100))}%`;if(text)$("loadingText").textContent=text}
function showLoading(text){$("loading").classList.add("show");$("loadingText").textContent=text;$("tableWrapper").classList.remove("show");$("stats").classList.remove("show");$("noResults").classList.remove("show");$("searchBtn").disabled=true;$("resultMeta").textContent="擷取中"}
function stopLoading(){$("loading").classList.remove("show");$("searchBtn").disabled=false}
function clearResults(){currentData=[];for(const id of ["errorMessage","successMessage"])$(id).classList.remove("show");$("tableWrapper").classList.remove("show");$("stats").classList.remove("show");$("noResults").classList.remove("show");$("logWrap").classList.remove("show");$("logPanel").replaceChildren();$("resultMeta").textContent="尚未搜尋"}
function message(id,text){$(id).textContent=text;$(id).classList.add("show")}
function validateRange(a,b){if(!a||!b)return"請選擇開始和結束日期";if(a>b)return"開始日期必須早於或等於結束日期";const days=Math.round((Date.parse(b)-Date.parse(a))/86400000)+1;if(days>CONFIG.maxDays)return`日期範圍不可超過 ${CONFIG.maxDays} 天`;if(b>=localYMD())return"歷史存檔最新資料來自昨天，結束日期不可選擇今天或未來日期";return""}
async function performSearch(){if(activeController)activeController.abort();activeController=new AbortController();clearResults();const m=mode(),name=$("vesselName").value.trim().toUpperCase(),type=$("dataType").value;try{showLoading("正在連接資料來源...");let data;if(m==="future")data=await fetchLiveSet("future",type);else if(m==="recent")data=await fetchRecentWithPorts(type);else{const a=$("startDate").value,b=$("endDate").value,err=validateRange(a,b);if(err){stopLoading();message("errorMessage",err);return}data=await fetchHistoricalRange(a,b,type)}if(name)data=data.filter(x=>x.vesselName.toUpperCase().includes(name));displayResults(data,name)}catch(e){if(e.name!=="AbortError"){log(e.message,"error");message("errorMessage",`未能完成搜尋：${e.message}`);$("resultMeta").textContent="擷取失敗"}stopLoading()}}
async function fetchLiveSet(group,type){const kinds=type==="both"?["arrival","departure"]:[type];log(group==="future"?"讀取未來船期":"讀取最近 36 小時資料");const settled=await Promise.allSettled(kinds.map(k=>fetchXML(CONFIG[group][k],k)));let all=[];settled.forEach((r,i)=>{if(r.status==="fulfilled"){all.push(...r.value);log(`${zhType(kinds[i])}：${r.value.length} 筆`,"success")}else log(`${zhType(kinds[i])}失敗：${r.reason.message}`,"error")});if(!all.length)throw new Error("所有指定資料來源均未能取得資料");return dedupe(all)}
async function fetchRecentWithPorts(type){const data=await fetchLiveSet("recent",type);setProgress(1,2,"正在補充上一靠港／下一靠港...");const kinds=type==="both"?["arrival","departure"]:[type];const maps=await Promise.all(kinds.map(async k=>{try{return portMap(await fetchXML(CONFIG.report[k],k),k)}catch(e){log(`${zhType(k)}靠港資料暫時未能取得`,"warn");return new Map}}));const combined=new Map;maps.forEach(m=>m.forEach((v,k)=>combined.set(k,v)));data.forEach(r=>r.adjacentPort=combined.get(callKey(r.callSign))||r.adjacentPort||"");return data}
async function fetchHistoricalRange(start,end,type){const days=[];for(let d=start;d<=end;d=addDays(d,1))days.push(d);const kinds=type==="both"?["arrival","departure"]:[type],tasks=[];for(const day of days)for(const kind of kinds)tasks.push(()=>fetchHistoricalDay(day,kind));let done=0;const results=await runPool(tasks,CONFIG.concurrency,()=>setProgress(++done,tasks.length,`正在獲取歷史資料 (${done}/${tasks.length})...`));const ok=results.filter(Boolean).flat();if(!ok.length)throw new Error("所選日期的歷史存檔均未能取得");return dedupe(ok)}
async function fetchHistoricalDay(day,kind){/* A morning snapshot on D+1 normally contains the complete records for D. */const snapshotDay=addDays(day,1),times=[`${snapshotDay.replaceAll("-","")}-1030`,`${snapshotDay.replaceAll("-","")}-1200`,`${day.replaceAll("-","")}-2330`];for(const t of times){try{const mainUrl=historyURL(CONFIG.recent[kind],t),reportUrl=historyURL(CONFIG.report[kind],t);const [records,report]=await Promise.all([fetchXML(mainUrl,kind,{retries:1}),fetchXML(reportUrl,kind,{retries:1}).catch(()=>[])]);const exact=records.filter(r=>datePart(r.time)===day),ports=portMap(report,kind);exact.forEach(r=>r.adjacentPort=ports.get(callKey(r.callSign))||"");if(exact.length){log(`${day} ${zhType(kind)}：${exact.length} 筆`,"success");return exact}}catch(e){log(`${day} ${zhType(kind)}取樣 ${t} 未成功`,"warn")}}log(`${day} ${zhType(kind)}沒有可用存檔`,"error");return[]}
function historyURL(raw,time){return`${CONFIG.historicalApi}?url=${encodeURIComponent(raw)}&time=${encodeURIComponent(time)}`}
async function runPool(tasks,limit,onDone){const out=new Array(tasks.length);let next=0;async function worker(){while(true){const i=next++;if(i>=tasks.length)return;try{out[i]=await tasks[i]()}catch{out[i]=[]}onDone()}}await Promise.all(Array.from({length:Math.min(limit,tasks.length)},worker));return out}
async function fetchXML(url,kind,options={}){const candidates=[url,...CONFIG.proxies.map(p=>p(url))],retries=options.retries??CONFIG.retries;let last="";for(let attempt=0;attempt<retries;attempt++){for(const target of candidates){try{const text=await fetchText(target);const rows=parseXML(text,kind);if(rows.length)return rows;last="XML 內沒有可辨識紀錄"}catch(e){if(e.name==="AbortError")throw e;last=e.message}}if(attempt+1<retries)await sleep(350*2**attempt)}throw new Error(last||"資料來源沒有回應")}
async function fetchText(url){const timeout=new AbortController(),timer=setTimeout(()=>timeout.abort(),CONFIG.timeoutMs),parent=activeController?.signal;const abort=()=>timeout.abort();parent?.addEventListener("abort",abort,{once:true});try{const res=await fetch(url,{cache:"no-store",redirect:"follow",signal:timeout.signal,headers:{Accept:"application/xml,text/xml,*/*"}});if(!res.ok)throw new Error(`HTTP ${res.status}`);const text=await res.text();if(text.length<40||/<html/i.test(text))throw new Error("回應不是有效 XML");return text}finally{clearTimeout(timer);parent?.removeEventListener("abort",abort)}}
function parseXML(text,kind){const doc=new DOMParser().parseFromString(text,"application/xml");if(doc.querySelector("parsererror"))throw new Error("XML 格式錯誤");let nodes=[...doc.querySelectorAll("G_SQL1,Record,record,RECORD,row,Row,ROW")];if(!nodes.length)nodes=[...doc.documentElement.children].filter(n=>n.children.length);return nodes.map(n=>parseRecord(n,kind)).filter(r=>r.vesselName)}
function value(node,names){for(const name of names){const target=[...node.getElementsByTagName("*")].find(e=>e.localName.toUpperCase()===name.toUpperCase());const v=target?.textContent?.trim();if(v)return v}return""}
function parseRecord(n,kind){const arrival=kind==="arrival";return{vesselName:value(n,["VESSEL_NAME","VesselName","SHIP_NAME"]),type:arrival?"抵港":"離港",time:value(n,arrival?["ATA_TIME","ARRIVAL_TIME","ETA_TIME","ETA"]:["ATD_TIME","DEPARTURE_TIME","ETD_TIME","ETD"]),location:value(n,arrival?["CURRENT_LOCATION","ANCHORAGE","BERTH"]:["LAST_BERTH","DEPARTURE_BERTH","BERTH"]),shipType:value(n,["SHIP_TYPE","Vessel_Type"]),callSign:value(n,["CALL_SIGN","CallSign"]),agentName:value(n,["AGENT_NAME","AgentName"]),adjacentPort:value(n,arrival?["LAST_PORT"]:["NEXT_PORT"]),remark:value(n,["REMARK"])} }
function callKey(v){return String(v||"").trim().toUpperCase().replace(/\s+/g,"")}
function portMap(rows,kind){const m=new Map;for(const r of rows)if(callKey(r.callSign)&&r.adjacentPort)m.set(callKey(r.callSign),r.adjacentPort);return m}
function datePart(v){const d=parseDate(v);if(!d)return"";return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function parseDate(v){if(!v)return null;const s=String(v).trim(),m=s.match(/^(\d{1,2})[-/]([A-Za-z]{3})[-/](\d{4})(?:\s+(\d{1,2}):(\d{2})(?::(\d{2}))?)?/),months={JAN:0,FEB:1,MAR:2,APR:3,MAY:4,JUN:5,JUL:6,AUG:7,SEP:8,OCT:9,NOV:10,DEC:11};if(m)return new Date(+m[3],months[m[2].toUpperCase()],+m[1],+(m[4]||0),+(m[5]||0),+(m[6]||0));const iso=s.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})(?:[ T](\d{1,2}):(\d{2}))?/);return iso?new Date(+iso[1],+iso[2]-1,+iso[3],+(iso[4]||0),+(iso[5]||0)):null}
function recordKey(r){return[r.type,r.vesselName.toUpperCase(),r.time,r.location,r.callSign].join("|")}
function dedupe(rows){const map=new Map;for(const r of rows){const k=recordKey(r);if(!map.has(k))map.set(k,r);else if(!map.get(k).adjacentPort&&r.adjacentPort)map.get(k).adjacentPort=r.adjacentPort}return[...map.values()]}
function zhType(k){return k==="arrival"?"抵港":"離港"}
function displayResults(data,term){stopLoading();data=dedupe(data).sort((a,b)=>(parseDate(a.time)?.getTime()??Infinity)-(parseDate(b.time)?.getTime()??Infinity)||a.vesselName.localeCompare(b.vesselName));currentData=data;if(!data.length){$("noResults").classList.add("show");$("resultMeta").textContent="0 筆記錄";return}message("successMessage",`成功載入 ${data.length} 筆記錄`);$("resultMeta").textContent=`${data.length} 筆記錄`;const arrivals=data.filter(r=>r.type==="抵港").length;$("stats").innerHTML=stat(data.length,"總記錄數")+stat(arrivals,"抵港")+stat(data.length-arrivals,"離港");$("stats").classList.add("show");createTable(data,term)}
function stat(v,l){return`<div class="stat-item"><div class="value">${v}</div><div class="label">${l}</div></div>`}
function createTable(data,term){const cols=[["type","類型"],["vesselName","船隻名稱"],["time","時間"],["location","位置"],["adjacentPort","上一靠港／下一靠港"],["shipType","船舶類型"],["agentName","代理"]];const tr=document.createElement("tr");for(const[,label]of cols){const th=document.createElement("th");th.textContent=label;tr.append(th)}$("tableHead").replaceChildren(tr);const frag=document.createDocumentFragment();for(const r of data){const row=document.createElement("tr");for(const[key]of cols){const td=document.createElement("td"),v=r[key]||"-";if(key==="type"){const b=document.createElement("span");b.className=`badge ${v==="抵港"?"badge-arrival":"badge-departure"}`;b.textContent=v;td.append(b)}else{td.textContent=v;if(term&&String(v).toUpperCase().includes(term))td.classList.add("highlight")}row.append(td)}frag.append(row)}$("tableBody").replaceChildren(frag);$("tableWrapper").classList.add("show")}
function clearSearch(){if(activeController)activeController.abort();$("vesselName").value="";$("dataType").value="both";$("useLast36h").checked=true;$("useFuture").checked=false;setDefaultDates();selectMode("recent",true);stopLoading();clearResults()}
