"use strict";
const CONFIG={
  arrivalUrl:"https://www.mardep.gov.hk/e_files/en/opendata/RP05005i.XML",
  departureUrl:"https://www.mardep.gov.hk/e_files/en/opendata/RP05505i.XML",
  arrivalReportUrl:"https://www.mardep.gov.hk/e_files/en/pub_services/RP05005.XML",
  departureReportUrl:"https://www.mardep.gov.hk/e_files/en/pub_services/RP05505.XML",
  futureArrivalUrl:"https://www.mardep.gov.hk/e_files/en/pub_services/RP04005.XML",
  futureDepartureUrl:"https://www.mardep.gov.hk/e_files/en/pub_services/RP04505.XML",
  historicalApiBase:"https://app.data.gov.hk/v1/historical-archive/get-file",
  corsProxies:["https://api.allorigins.win/raw?url=","https://corsproxy.io/?"],
  maxDays:20,maxFetchAttempts:10,retryBaseDelayMs:250,cachePrefix:"mardep-v3:"
};
let currentData=[];
const $=id=>document.getElementById(id);
document.addEventListener("DOMContentLoaded",()=>{setDefaultDates();$("useLast36h").addEventListener("change",()=>syncMode("recent"));$("useFuture").addEventListener("change",()=>syncMode("future"));$("startDate").addEventListener("change",()=>{if(!$("useLast36h").checked&&!$("useFuture").checked){$("endDate").focus();if(typeof $("endDate").showPicker==="function")$("endDate").showPicker()}});$("searchBtn").addEventListener("click",performSearch);$("clearBtn").addEventListener("click",clearSearch);$("vesselName").addEventListener("keydown",e=>{if(e.key==="Enter")performSearch()});syncMode("recent",true)});
function setDefaultDates(){const today=localYMD(new Date()),yesterday=localYMD(new Date(Date.now()-86400000));$("startDate").value=yesterday;$("endDate").value=today}
function localYMD(d){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Hong_Kong",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(d),v=Object.fromEntries(p.map(x=>[x.type,x.value]));return`${v.year}-${v.month}-${v.day}`}
function syncMode(changed,initial=false){const recent=$("useLast36h"),future=$("useFuture");if(changed==="recent"&&recent.checked)future.checked=false;if(changed==="future"&&future.checked)recent.checked=false;const special=recent.checked||future.checked;$("startDate").disabled=special;$("endDate").disabled=special;$("modeHint").textContent=future.checked?"未來船期直接讀取海事處最新 XML，日期範圍不適用。":recent.checked?"可查詢最近 36 小時，或取消勾選查詢最多 20 天的歷史資料。":"可選擇最多 20 天的歷史日期範圍。";if(!initial)clearResults()}
function sleep(ms){return new Promise(r=>setTimeout(r,ms))}
function escapeHTML(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function log(message,type="info"){const time=new Date().toLocaleTimeString("zh-HK",{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:false}),e=document.createElement("div");e.innerHTML=`<span class="log-time">[${escapeHTML(time)}]</span> <span class="log-${type}">${escapeHTML(message)}</span>`;$("logPanel").appendChild(e);$("logWrap").classList.add("show");$("logPanel").scrollTop=$("logPanel").scrollHeight}
function clearMessages(){document.querySelectorAll(".message").forEach(el=>el.classList.remove("show"))}
function showMessage(id,text){$(id).textContent=text;$(id).classList.add("show")}
function showLoading(text){$("loading").classList.add("show");$("loadingText").textContent=text||"正在獲取資料...";$("progressBar").style.width="8%";$("tableWrapper").classList.remove("show");$("stats").classList.remove("show");$("noResults").classList.remove("show");$("searchBtn").disabled=true;$("resultMeta").textContent="擷取中"}
function hideLoading(){$("loading").classList.remove("show");$("searchBtn").disabled=false}
function clearResults(){currentData=[];clearMessages();$("tableWrapper").classList.remove("show");$("stats").classList.remove("show");$("noResults").classList.remove("show");$("logWrap").classList.remove("show");$("logPanel").replaceChildren();$("resultMeta").textContent="尚未搜尋"}
function validateDateRange(start,end){if(!start||!end)return{valid:false,error:"請選擇開始和結束日期"};if(new Date(start)>new Date(end))return{valid:false,error:"開始日期必須早於結束日期"};const days=Math.ceil((new Date(end)-new Date(start))/86400000)+1;if(days>CONFIG.maxDays)return{valid:false,error:`日期範圍不可超過 ${CONFIG.maxDays} 天`};return{valid:true,days}}
function parseVesselDateTime(value){if(!value)return null;const s=String(value).trim(),m=s.match(/^(\d{1,2})-([A-Za-z]{3})-(\d{4})(?:\s+(\d{1,2}):(\d{2})(?::(\d{2}))?)?/),months={JAN:0,FEB:1,MAR:2,APR:3,MAY:4,JUN:5,JUL:6,AUG:7,SEP:8,OCT:9,NOV:10,DEC:11};if(m){const d=new Date(+m[3],months[m[2].toUpperCase()],+m[1],+(m[4]||0),+(m[5]||0),+(m[6]||0));return Number.isNaN(d.getTime())?null:d}const d=new Date(s);return Number.isNaN(d.getTime())?null:d}
function filterBySelectedDateRange(data,startStr,endStr){const start=new Date(startStr),end=new Date(endStr);start.setHours(0,0,0,0);end.setHours(23,59,59,999);return data.filter(x=>{const d=parseVesselDateTime(x.time);return d&&d>=start&&d<=end})}
function sortByTimeAscending(data){return data.slice().sort((a,b)=>(parseVesselDateTime(a.time)?.getTime()??Infinity)-(parseVesselDateTime(b.time)?.getTime()??Infinity)||(a.vesselName||"").localeCompare(b.vesselName||""))}
function floorToHalfHourHHMM(date){const d=new Date(date);d.setMinutes(d.getMinutes()<30?0:30,0,0);return`${String(d.getHours()).padStart(2,"0")}${String(d.getMinutes()).padStart(2,"0")}`}
function ymd(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function recordKey(r){return`${(r.vesselName||"").toUpperCase()}|${r.type||""}|${r.time||""}|${r.location||""}|${r.callSign||""}`}
function dedupeRecords(records){const seen=new Map;for(const r of records){const k=recordKey(r);if(!seen.has(k))seen.set(k,r);else if(!seen.get(k).adjacentPort&&r.adjacentPort)seen.get(k).adjacentPort=r.adjacentPort}return[...seen.values()]}
function callKey(v){return String(v||"").trim().toUpperCase().replace(/\s+/g,"")}
function portMap(rows){const map=new Map;for(const r of rows)if(callKey(r.callSign)&&r.adjacentPort)map.set(callKey(r.callSign),r.adjacentPort);return map}
async function performSearch(){clearResults();const vesselName=$("vesselName").value.trim().toUpperCase(),type=$("dataType").value;try{let data;if($("useFuture").checked){showLoading("正在獲取未來船期...");data=await searchCurrentMode("future",vesselName,type)}else if($("useLast36h").checked){showLoading("正在獲取最近 36 小時船隻資料...");data=await searchCurrentMode("recent",vesselName,type)}else{const start=$("startDate").value,end=$("endDate").value,v=validateDateRange(start,end);if(!v.valid){showMessage("errorMessage",v.error);return}showLoading("正在獲取歷史資料...");log(`日期範圍：${start} 至 ${end}（${v.days} 天）`);const all=await fetchHistoricalDataRangeOptimized(start,end,type);data=filterBySelectedDateRange(all,start,end);if(vesselName)data=data.filter(x=>x.vesselName?.toUpperCase().includes(vesselName))}displayResults(data,vesselName)}catch(e){log(`錯誤：${e.message}`,"error");showMessage("errorMessage",`搜尋時發生錯誤：${e.message}`);$("resultMeta").textContent="擷取失敗";hideLoading()}}
async function searchCurrentMode(mode,name,type){let all=[],arrivalCount=0,departureCount=0;const isFuture=mode==="future",aUrl=isFuture?CONFIG.futureArrivalUrl:CONFIG.arrivalUrl,dUrl=isFuture?CONFIG.futureDepartureUrl:CONFIG.departureUrl;if(type==="both"||type==="arrival"){log("獲取抵港資料...");const rows=await fetchXMLDataEnsured(aUrl,"arrival",false,5);arrivalCount=rows.length;all.push(...rows);log(`抵港：${rows.length} 筆`,"success")}if(type==="both"||type==="departure"){if(type==="both"){log("等待後再獲取離港資料...");await sleep(1500)}log("獲取離港資料...");const rows=await fetchXMLDataEnsured(dUrl,"departure",false,5);departureCount=rows.length;all.push(...rows);log(`離港：${rows.length} 筆`,"success")}if(!isFuture){$("loadingText").textContent="正在補充上一靠港／下一靠港...";await attachCurrentPorts(all,type)}if(name)all=all.filter(x=>x.vesselName?.toUpperCase().includes(name));log(`完成：共 ${all.length} 筆記錄（抵港 ${arrivalCount}，離港 ${departureCount}）`,"success");return dedupeRecords(all)}
async function attachCurrentPorts(rows,type){const jobs=[];if(type==="both"||type==="arrival")jobs.push(fetchXMLDataEnsured(CONFIG.arrivalReportUrl,"arrival",false,5).catch(e=>{log(`抵港靠港資料未能取得：${e.message}`,"warn");return[]}));if(type==="both"||type==="departure")jobs.push(fetchXMLDataEnsured(CONFIG.departureReportUrl,"departure",false,5).catch(e=>{log(`離港靠港資料未能取得：${e.message}`,"warn");return[]}));const maps=(await Promise.all(jobs)).map(portMap),combined=new Map;maps.forEach(m=>m.forEach((v,k)=>combined.set(k,v)));rows.forEach(r=>r.adjacentPort=combined.get(callKey(r.callSign))||r.adjacentPort||"")}
async function fetchHistoricalDataRangeOptimized(startDate,endDate,dataType="both"){const start=new Date(startDate),end=new Date(endDate),todayStr=ymd(new Date()),all=[],seen=new Set(),total=Math.ceil((end-start)/86400000)+1;let index=0,failed=0;for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){index++;const dayStr=ymd(d),hhmm=dayStr>=todayStr?floorToHalfHourHHMM(new Date()):"2330",timeParam=`${dayStr.replaceAll("-","")}-${hhmm}`;showLoading(`正在獲取 ${dayStr} 的資料（${index}/${total}）...`);$("progressBar").style.width=`${Math.round(index/total*100)}%`;log(`[${index}/${total}] ${dayStr} → 取樣點 ${hhmm}`);const needA=dataType==="both"||dataType==="arrival",needD=dataType==="both"||dataType==="departure";const [a,dpt]=await Promise.all([needA?fetchHistoricalDataSafe(CONFIG.arrivalUrl,timeParam,"arrival",dayStr):[],needD?fetchHistoricalDataSafe(CONFIG.departureUrl,timeParam,"departure",dayStr):[]]);if(needA&&needD&&!a.length&&!dpt.length)failed++;for(const item of [...a,...dpt]){const k=recordKey(item);if(!seen.has(k)){seen.add(k);all.push(item)}}await attachHistoricalPorts(all.filter(r=>{const dt=parseVesselDateTime(r.time);return dt&&ymd(dt)===dayStr}),timeParam,dataType);log(`→ 抵港 ${a.length}，離港 ${dpt.length}`,"success");if(index<total)await sleep(800)}if(failed)log(`注意：${failed} 天的資料未能取得`,"warn");return all}
async function attachHistoricalPorts(dayRows,timeParam,type){const jobs=[];if(type==="both"||type==="arrival")jobs.push(fetchHistoricalDataSafe(CONFIG.arrivalReportUrl,timeParam,"arrival","靠港").then(portMap));if(type==="both"||type==="departure")jobs.push(fetchHistoricalDataSafe(CONFIG.departureReportUrl,timeParam,"departure","靠港").then(portMap));const combined=new Map;(await Promise.all(jobs)).forEach(m=>m.forEach((v,k)=>combined.set(k,v)));dayRows.forEach(r=>r.adjacentPort=combined.get(callKey(r.callSign))||r.adjacentPort||"")}
async function fetchHistoricalDataSafe(rawUrl,timeParam,type,day){try{return await fetchHistoricalDataEnsured(rawUrl,timeParam,type)}catch(e){log(`${day} ${type==="arrival"?"抵港":"離港"}資料取得失敗：${e.message}`,"error");return[]}}
async function fetchHistoricalDataEnsured(rawUrl,timeParam,type){const url=`${CONFIG.historicalApiBase}?url=${encodeURIComponent(rawUrl)}&time=${timeParam}`;return fetchXMLDataEnsured(url,type,true)}
function cacheKey(url,type){let h=2166136261;for(const c of url){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return`${CONFIG.cachePrefix}${type}:${h>>>0}`}
function readCache(url,type){try{const v=JSON.parse(localStorage.getItem(cacheKey(url,type)));return v&&v.xml?v:null}catch{return null}}
function writeCache(url,type,xml){try{localStorage.setItem(cacheKey(url,type),JSON.stringify({savedAt:Date.now(),xml}))}catch{}}
async function fetchXMLDataEnsured(url,type,isHistorical,maxAttempts=null){const attempts=maxAttempts||CONFIG.maxFetchAttempts;for(let attempt=1;attempt<=attempts;attempt++){log(`${isHistorical?"歷史 API":"即時 XML"} 連線中...（第 ${attempt}/${attempts} 次）`);const result=await fetchXMLDataOnce(url,type,attempt);if(result.data.length){writeCache(url,type,result.xml);return result.data}const delay=Math.max(1000,CONFIG.retryBaseDelayMs*attempt*4);log(`未取到資料，${delay}ms 後重試...`,"warn");await sleep(delay)}const cached=readCache(url,type);if(cached){log(`連線失敗，改用最近成功快取（${new Date(cached.savedAt).toLocaleString("zh-HK")}）`,"warn");const rows=parseVesselXML(cached.xml,type);if(rows.length)return rows}throw new Error("無法從資料來源取得任何資料（已多次重試）")}
async function fetchXMLDataOnce(url,type,attemptNumber){const isMardep=url.includes("mardep.gov.hk")&&!url.includes("historical-archive");if(!isMardep){const direct=await tryFetchAndParse(url,type);if(direct.data.length)return direct}const start=((attemptNumber||1)-1)%CONFIG.corsProxies.length;for(let j=0;j<CONFIG.corsProxies.length;j++){const i=(start+j)%CONFIG.corsProxies.length,proxy=CONFIG.corsProxies[i]+encodeURIComponent(url),via=await tryFetchAndParse(proxy,type);if(via.data.length)return via;if(j<CONFIG.corsProxies.length-1)await sleep(500)}return{data:[],xml:""}}
async function tryFetchAndParse(url,type){try{const response=await fetch(url,{cache:"no-store"});if(!response.ok)return{data:[],xml:""};const xml=await response.text();if(xml.length<80||!(xml.includes("<?xml")||xml.includes("<RP0")||xml.includes("<G_SQL")))return{data:[],xml:""};return{data:parseVesselXML(xml,type),xml}}catch{return{data:[],xml:""}}}
function parseVesselXML(xmlText,type){const doc=new DOMParser().parseFromString(xmlText,"text/xml");if(doc.querySelector("parsererror"))return[];let records=[];for(const selector of ["G_SQL1","Record","record","RECORD","row","Row","ROW"]){records=[...doc.getElementsByTagName(selector)];if(records.length)break}if(!records.length&&doc.documentElement?.children.length)records=[...doc.documentElement.children];return records.map(el=>parseVesselRecord(el,type)).filter(r=>r.vesselName)}
function parseVesselRecord(element,type){
  const getVal=names=>{
    for(const name of names){
      const target=element.querySelector(name)||element.getElementsByTagName(name)[0];
      if(target?.textContent)return target.textContent.trim();
    }
    return "";
  };
  const arrival=type==="arrival";
  return{
    vesselName:getVal(["VESSEL_NAME","Vessel_Name","vessel_name","VesselName"]),
    type:arrival?"抵港":"離港",
    time:getVal(arrival
      ?["ATA_TIME","ARRIVAL_TIME","Arrival_Time","ETA_TIME","ETA"]
      :["ATD_TIME","DEPARTURE_TIME","Departure_Time","ETD_TIME","ETD","DEP_TIME"]),
    location:getVal(arrival
      ?["CURRENT_LOCATION","Current_Location","ANCHORAGE","BERTH"]
      :["LAST_BERTH","Last_Berth","BERTH","DEPARTURE_BERTH"]),
    shipType:getVal(["SHIP_TYPE","Ship_Type","ShipType"]),
    callSign:getVal(["CALL_SIGN","Call_Sign","CallSign"]),
    agentName:getVal(["AGENT_NAME","Agent_Name","AgentName"]),
    adjacentPort:getVal(arrival?["LAST_PORT","Last_Port"]:["NEXT_PORT","Next_Port"]),
    remark:getVal(["REMARK","Remark"])
  };
}

function displayResults(data,term){hideLoading();const sorted=sortByTimeAscending(dedupeRecords(Array.isArray(data)?data:[]));currentData=sorted;if(!sorted.length){$("noResults").classList.add("show");$("resultMeta").textContent="0 筆記錄";return}showMessage("successMessage",`找到 ${sorted.length} 筆記錄`);$("resultMeta").textContent=`${sorted.length} 筆記錄`;const a=sorted.filter(r=>r.type==="抵港").length;$("stats").innerHTML=stat(sorted.length,"總記錄數")+stat(a,"抵港")+stat(sorted.length-a,"離港");$("stats").classList.add("show");createTable(sorted,term)}
function stat(value,label){return`<div class="stat-item"><div class="value">${value}</div><div class="label">${label}</div></div>`}
function createTable(data,term){const isFuture=$("useFuture").checked;let cols=[["type","類型"],["vesselName","船隻名稱"],["time","時間"],["location","位置"],["adjacentPort","上一靠港／下一靠港"],["shipType","船舶類型"],["agentName","代理"]];if(isFuture)cols=cols.filter(c=>c[0]!=="location");const head=document.createElement("tr");for(const[,label]of cols){const th=document.createElement("th");th.textContent=label;head.appendChild(th)}$("tableHead").replaceChildren(head);const frag=document.createDocumentFragment();for(const record of data){const row=document.createElement("tr");for(const[key]of cols){const td=document.createElement("td"),value=record[key]||"-";if(key==="type"){const badge=document.createElement("span");badge.className=`badge ${value==="抵港"?"badge-arrival":"badge-departure"}`;badge.textContent=value;td.appendChild(badge)}else{td.textContent=value;if(term&&String(value).toUpperCase().includes(term))td.classList.add("highlight")}row.appendChild(td)}frag.appendChild(row)}$("tableBody").replaceChildren(frag);$("tableWrapper").classList.add("show")}
function clearSearch(){$("vesselName").value="";$("dataType").value="both";$("useLast36h").checked=true;$("useFuture").checked=false;setDefaultDates();syncMode("recent",true);hideLoading();clearResults()}
